CREATE TABLE `app_deployments` (
	`id` text PRIMARY KEY NOT NULL,
	`app_name` text NOT NULL,
	`description` text,
	`docker_image` text NOT NULL,
	`port` integer DEFAULT 3000 NOT NULL,
	`solana_treasury_public_key` text,
	`solana_treasury_secret_cipher` text,
	`solana_treasury_secret_iv` text,
	`akash_address` text,
	`akash_mnemonic_cipher` text,
	`akash_mnemonic_iv` text,
	`status` text DEFAULT 'PENDING_FUNDS' NOT NULL,
	`akash_dseq` text,
	`akash_provider` text,
	`akash_chain_result` text,
	`last_error` text,
	`deploy_attempt_count` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `deploy_workflow_runs` (
	`id` text PRIMARY KEY NOT NULL,
	`deployment_id` text NOT NULL,
	`attempt` integer DEFAULT 1 NOT NULL,
	`phase` text DEFAULT 'CERT' NOT NULL,
	`phase_started_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`akash_owner` text,
	`tls_cert_pem` text,
	`tls_key_pem` text,
	`dseq` text,
	`provider` text,
	`gseq` integer,
	`oseq` integer,
	`provider_host_uri` text,
	`lease_status` text,
	`forwarded_ports` text,
	`warnings` text DEFAULT '[]' NOT NULL,
	`error` text,
	`manifest_claimed_at` integer,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	FOREIGN KEY (`deployment_id`) REFERENCES `app_deployments`(`id`) ON UPDATE no action ON DELETE cascade
);
